sylius_twig_hooks:
    hooks:
        'sylius_admin.customer.show.content.sections':
            loyalty:
                template: '@SyliusLoyaltyPlugin/admin/customer/show/content/sections/loyalty.html.twig'
                priority: 50
