sylius_twig_hooks:
    hooks:
        'sylius_shop.cart.index.content.form.sections.general#left':
            loyalty_points:
                template: '@SyliusLoyaltyPlugin/shop/cart/index/content/form/sections/general/loyalty_points.html.twig'
                priority: 90

        'sylius_shop.cart.index.content.form.sections.general.summary':
            loyalty_discount:
                template: '@SyliusLoyaltyPlugin/shop/cart/index/content/form/sections/general/summary/loyalty_discount.html.twig'
                priority: 350

        'sylius_shop.checkout.common.sidebar.summary.total':
            loyalty_discount:
                template: '@SyliusLoyaltyPlugin/shop/checkout/common/sidebar/summary/total/loyalty_discount.html.twig'
                priority: 250
