sylius_grid:
    grids:
        loyalty_admin_loyalty_earning_rule:
            driver:
                name: doctrine/orm
                options:
                    class: '%loyalty.model.earning_rule.class%'
                    repository:
                        method: createQueryBuilder
                        arguments: ['er']
            sorting:
                name: asc
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                channels:
                    type: twig
                    label: sylius.ui.channels
                    path: "."
                    options:
                        template: '@SyliusLoyaltyPlugin/admin/loyalty_earning_rule/field/channels.html.twig'
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: '@SyliusUi/grid/field/enabled.html.twig'
            filters:
                name:
                    type: string
                    label: sylius.ui.name
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            actions:
                main:
                    create:
                        type: create
                        label: loyalty.ui.add_earning_rule
                        options:
                            link:
                                route: loyalty_admin_earning_rule_create
                item:
                    update:
                        type: update
                        options:
                            link:
                                route: loyalty_admin_earning_rule_update
                                parameters:
                                    id: resource.id
                    delete:
                        type: delete
