sylius_grid:
    grids:
        loyalty_admin_loyalty_earning_rule:
            driver:
                name: doctrine/orm
                options:
                    class: '%loyalty.model.earning_rule.class%'
                    repository:
                        method: createQueryBuilder
                        arguments: ['er']
            sorting:
                priority: desc
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                scopeType:
                    type: twig
                    label: loyalty.ui.scope_type
                    options:
                        template: '@SyliusLoyaltyPlugin/admin/loyalty_earning_rule/field/scope_type.html.twig'
                targetCodes:
                    type: twig
                    label: loyalty.ui.target
                    options:
                        template: '@SyliusLoyaltyPlugin/admin/loyalty_earning_rule/field/target.html.twig'
                pointsPerCurrencyUnit:
                    type: string
                    label: loyalty.ui.points_per_unit
                    sortable: ~
                priority:
                    type: string
                    label: sylius.ui.priority
                    sortable: ~
                conflicts:
                    type: twig
                    label: loyalty.ui.conflicts
                    path: "."
                    options:
                        template: '@SyliusLoyaltyPlugin/admin/loyalty_earning_rule/field/conflicts.html.twig'
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: '@SyliusUi/grid/field/enabled.html.twig'
            filters:
                name:
                    type: string
                    label: sylius.ui.name
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
